---
- name: Act on lambda infraestructure
  include_tasks: deploy.yml

- name: Check if remote repo exists
  command: 'gh repo view auto-processor/{{ item.name }}'
  changed_when: false
  ignore_errors: true
  register: result

- name: Create GitHub repo and start workflow if it does not exist
  include_tasks: deploy_first_time.yml
  when: result is failed
