---
- name: Create repo from template
  command: >
    gh repo create auto-processor/{{ item.name }} --public
    --template auto-processor/lambda-service-template
  changed_when: true

- name: Clone repo
  ansible.builtin.git:
    repo: 'https://github.com/auto-processor/{{ item.name }}.git'
    dest: service
    version: main

- name: Add repo vars
  ansible.builtin.template:
    src: cookiecutter.json.j2
    dest: service/cookiecutter.json
    mode: '0644'

- name: Create repo from template
  command:
    cmd: "{{ push }}"
    chdir: service
  loop:
    - git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - git config --global user.name "github-actions[bot]"
    - git checkout -b temp-branch
    - git add .
    - git commit -m 'Initial commit'
    - git push origin temp-branch:main
  loop_control:
    loop_var: push
  changed_when: true

- name: remove cloned repo
  ansible.builtin.file:
    path: service
    state: absent
    mode: '0644'
