---
- name: "Act on {{ item.name }} lambda role"
  community.aws.iam_role:
    name: "{{ item.name }}LambdaRole"
    assume_role_policy_document: "{{ lookup('template','lambda_role.json.j2') }}"
    description: "This is the {{ item.name }} role"
  register: lambda_role

- name: 'Create the {{ item.name }} policy'
  community.aws.iam_policy:
    iam_type: role
    iam_name: '{{ lambda_role.role_name }}'
    policy_name: '{{ item.name }}-policy'
    state: present
    policy_json: "{{ lookup( 'template', 'lambda_policy.json.j2') }}"