name: Deploy services
on:
  push:
    branches: [ main ]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: services.yaml
          override-deps: |
            rich>=9.5.1,<11.0.0
  deploy:
    env:
      REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
    runs-on: ubuntu-latest
    needs:
      - ansible-lint
    steps:
      - uses: actions/checkout@v2
      - run: pip install boto3
      - name: Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run playbook
        env:
          GITHUB_TOKEN: ${{ env.REPO_SETUP_TOKEN }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: services.yaml
          inventory: |
            localhost ansible_connection=local
