name: Deploy infra
on:
  push:
    branches: [ main ]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: ""
          override-deps: |
            ansible==2.9
            ansible-lint==4.2.0
  deploy:
    runs-on: ubuntu-latest
    needs:
      - ansible-lint
    steps:
      - uses: actions/checkout@v2
      - run: pip install boto3
      - name: Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: transactors.yaml
          inventory: |
            localhost ansible_connection=local
          options: |
            --extra-vars license_key=${{ secrets.DATOMIC_LICENSE_KEY }}
