name: Lint
on:
  push:
    branches: ["!main"]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            services.yaml
            transactors.yaml
          override-deps: |
            rich>=9.5.1,<11.0.0