name: Transactors
on:
  workflow_run:
    workflows: [ "Lint" ]
    branches: [ main ]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install boto3
      - name: Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: transactors.yaml
          directory: ./playbooks
          inventory: |
            localhost ansible_connection=local
          options: |
            --extra-vars license_key=${{ secrets.DATOMIC_LICENSE_KEY }}
